image: "python:3.9"

variables:
  BIOTRADE_SKIP_CONFIRMATION: "True"

before_script:
  - python --version
  - pip install .
  - pip install pytest

pytest:
  stage: test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
