image: "python:3.9"

variables:
  BIOTRADE_SKIP_CONFIRMATION: "True"
  BIOTRADE_DATA: "$CI_PROJECT_DIR/biotrade_data"

before_script:
  - python --version
  - pip install .
  - pip install pytest
  - echo $CI_PROJECT_DIR 
  - echo $BIOTRADE_DATA
  - pwd

stages:
  - convert
  - test

md-to-pdf:
  stage: convert
  tags:
    - inara
  image:
    name: openjournals/inara
    entrypoint: [""]
  script:
    - inara -p -o pdf paper/paper.md
  artifacts:
    paths:
      - paper.pdf

pytest:
  stage: test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
