image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install pytest

pytest:
  stage: test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
