image: "python:3.9"

before_script:
  - python --version
  - pip install .
  - pip install pytest

pytest:
  stage: test
  env:
    global:
      - BIOTRADE_SKIP_CONFIRMATION=1
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
